### ISSUE TITLE
Disabling or Uninstalling plugin doesn't revert back to original ways

### ISSUE THREAD

**Issue by dummifiedme** [shichongrui/obsidian-reveal-active-file#2]
I tried disabling and uninstalling the plugin after #1 issue, but it seems like the change is permanent. I am unable to revert back to the behaviour I had. Even without plugin it keeps revealing files and keeps opening sidebar every time I navigate. Super irritating :(

**Comment by dummifiedme** [comment]
Please suggest a way to fix it. 👎🏼

**Comment by shichongrui** [comment]
I wouldn't expect it to behave this way. I would expect it to stop doing it after uninstalling. I will try and see if I can find a way to fix this.
