### ISSUE TITLE
Shouldn't close search results when clicking on one result

### ISSUE THREAD

**Issue by Gattomarino** [shichongrui/obsidian-reveal-active-file#4]
When you click on a search result in the Search pane, the relevant note opens (as it should) BUT at the same time the search result list closes. It really should stay open IMHO.
EDIT: the issue persists after plugin is disabled and uninstalled, until Obsidian is closed and opened again.
Obsidian 0.10.13, macOS 10.12.6
Thanks!

**Comment by shichongrui** [comment]
Released as version 1.0.2
