### ISSUE TITLE
Unfortunately does not work anymore

### ISSUE THREAD

**Issue by cocoonkid** [shichongrui/obsidian-reveal-active-file#5]
Unfortunately does not work anymore

**Comment by tabdulradi** [comment]
I can see it highlights the open file, but it doesn't scroll to it.

**Comment by cocoonkid** [comment]
yes. I noticed that now too.

I will investigate further.

I also found that it does not automatically open collapsed folders.

Maybe the issues is somewhere hidden there.

**Comment by ngirard** [comment]
This is indeed annoying.

The `file-explorer:reveal-active-file` command does exactly that, so I'd suggest that the extension calls it.

**Comment by WhiteMac** [comment]
The developer seems unresponsive, but here is how you fix the plugin.

Instructions hopefully simple enough for even non-developers.

1. Open your Obsidian plugin folder.

You can do this from Obsidian > Settings > Community Plugins > Click the folder icon to the right of "Installed Plugins".

2. Quit Obsidian.

3. Back in your Obsidian plugin folder, open the folder obsidian-reveal-active-file.

Open the file main.js with a plain text editor like VSCode.

4. Find the line:

`_this.app.commands.executeCommandById('explorer:reveal-active-file');`

As at the time of my comment, this is on line 42.

5. Replace with:

`_this.app.commands.executeCommandById('file-explorer:reveal-active-file');`

6. Save.

You're done. Plugin should work fine when you start Obsidian back up.

**Comment by tyf2018** [comment]
> The developer seems unresponsive, but here is how you fix the plugin.
> 
> Instructions hopefully simple enough for even non-developers.
> 
> 1. Open your Obsidian plugin folder.
> 
> You can do this from Obsidian > Settings > Community Plugins > Click the folder icon to the right of "Installed Plugins".
> 
> 1. Quit Obsidian.
> 2. Back in your Obsidian plugin folder, open the folder obsidian-reveal-active-file.
> 3. Open the file main.js with a plain text editor like VSCode.
> 4. Find the line:
> 
> `_this.app.commands.executeCommandById('explorer:reveal-active-file');`
> 
> As at the time of my comment, this is on line 42.
> 
> 1. Replace with:
> 
> `_this.app.commands.executeCommandById('file-explorer:reveal-active-file');`
> 
> 1. Save.
> 
> You're done. Plugin should work fine when you start Obsidian back up.



> The developer seems unresponsive, but here is how you fix the plugin.
> 
> Instructions hopefully simple enough for even non-developers.
> 
> 1. Open your Obsidian plugin folder.
> 
> You can do this from Obsidian > Settings > Community Plugins > Click the folder icon to the right of "Installed Plugins".
> 
> 1. Quit Obsidian.
> 2. Back in your Obsidian plugin folder, open the folder obsidian-reveal-active-file.
> 3. Open the file main.js with a plain text editor like VSCode.
> 4. Find the line:
> 
> `_this.app.commands.executeCommandById('explorer:reveal-active-file');`
> 
> As at the time of my comment, this is on line 42.
> 
> 1. Replace with:
> 
> `_this.app.commands.executeCommandById('file-explorer:reveal-active-file');`
> 
> 1. Save.
> 
> You're done. Plugin should work fine when you start Obsidian back up.

After the modification, the situation has improved a lot and it is basically usable. Thank you very much.

**Comment by shichongrui** [comment]
> The developer seems unresponsive, but here is how you fix the plugin.

Sorry, life is busy. PRs are welcome and I can do a new release.

**Comment by fruchtblase** [comment]
hey everyone, I made a pull request out of the solution posted by @WhiteMac

**Comment by cocoonkid** [comment]
:heart:  for everyone here!

**Comment by ramisedhom** [comment]
I'll wait the new version to re-install it again.

**Comment by shichongrui** [comment]
Merged #6 and published new release 1.0.1
